openapi: 3.0.1
info:
  title: Weather
  version: '1.0.0'
  contact:
    name: API Support
  description: 'Weather API for retrieving weather forecasts'
servers:
  - url: https://ci-cd-apim-instance.azure-api.net/wt
paths:
  /weatherforecast:
    get:
      tags:
        - WebApplication1
      summary: GetWeatherForecast
      operationId: GetWeatherForecast
      description: Retrieves the weather forecast for the upcoming days.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WeatherForecast'
              example:
                - date: "2024-06-06"
                  temperatureC: 0
                  summary: string
                  temperatureF: 0
  '/weatherforecast/{weatherForecastId}':
    get:
      tags:
        - WebApplication1
      summary: '/weatherforecast/{weatherForecastId} - GET'
      operationId: GetWeatherForecastById
      description: Retrieves the weather forecast by ID.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
  /error:
    get:
      tags:
        - WebApplication1
      summary: /error - GET
      operationId: GetError
      description: Retrieves the error information.
      responses:
        '200':
          description: OK
  /serviceerror:
    get:
      tags:
        - WebApplication1
      summary: /serviceerror - GET
      operationId: GetServiceError
      description: Retrieves the service error information.
      responses:
        '200':
          description: OK
components:
  schemas:
    Project:
      type: object
      properties:
        name:
          type: string
          nullable: true
      additionalProperties: false
    WeatherForecast:
      type: object
      properties:
        date:
          type: string
          format: date
        temperatureC:
          type: integer
          format: int32
        summary:
          type: string
          nullable: true
        temperatureF:
          type: integer
          format: int32
          readOnly: true
      additionalProperties: false
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]
tags:
  - name: WebApplication1