openapi: 3.0.1
info:
  title: Project
  description: 'Project API for managing projects'
  version: '1.0.0'
  contact:
    name: API Support
servers:
  - url: https://ci-cd-apim-instance.azure-api.net/proj
paths:
  /project:
    post:
      summary: CreateProject
      description: Creating a project with schema validation in the Apim
      operationId: createproject
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/proj-schema'
            example:
              name: wipro
      responses:
        '201':
          description: Project Created
          content:
            application/json: { }
    get:
      summary: GetAllProjects
      description: Getting all the Projects
      operationId: getallprojects
      responses:
        '200':
          description: ''
components:
  schemas:
    proj-schema:
      type: object
      properties:
        name:
          type: string
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]