name: Run - Extractor

on:
  workflow_dispatch:
    inputs:
      CONFIGURATION_YAML_PATH:
        description: "Extract configuration"
        required: true
        type: choice
        options:
          - Extract All APIs
          - configuration.extractor.yaml

      API_SPECIFICATION_FORMAT:
        description: "API Specification Format"
        required: true
        type: choice
        options:
          - OpenAPIV3Yaml
          - OpenAPIV3Json
          - OpenAPIV2Yaml
          - OpenAPIV2Json

permissions:
  id-token: write
  contents: read

env:
  apiops_release_version: v7.0.4

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Run Extractor
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_RESOURCE_GROUP_NAME: ${{ vars.RESOURCE_GROUP }}
          API_MANAGEMENT_SERVICE_NAME: ${{ vars.APIM_NAME }}
          API_MANAGEMENT_SERVICE_OUTPUT_FOLDER_PATH: ${{ github.workspace }}/artifacts
          API_SPECIFICATION_FORMAT: ${{ github.event.inputs.API_SPECIFICATION_FORMAT }}
        shell: pwsh
        run: |
          $releaseFileName = "extractor-linux-x64.zip"
          $executableFileName = "extractor"

          $uri = "https://github.com/Azure/apiops/releases/download/${{ env.apiops_release_version }}/$releaseFileName"

          Write-Host "Downloading: $uri"

          $downloadFilePath = Join-Path "${{ runner.temp }}" $releaseFileName

          Invoke-WebRequest `
            -Uri $uri `
            -OutFile $downloadFilePath

          $executableFolderPath = Join-Path "${{ runner.temp }}" "extractor"

          Expand-Archive `
            -Path $downloadFilePath `
            -DestinationPath $executableFolderPath `
            -Force

          $executableFilePath = Join-Path $executableFolderPath $executableFileName

          chmod +x $executableFilePath

          & $executableFilePath

          if ($LASTEXITCODE -ne 0) {
            throw "Extractor failed"
          }

      - name: Show Extracted Files
        shell: bash
        run: |
          echo "Workspace:"
          pwd

          echo "Artifacts directory:"
          ls -la $GITHUB_WORKSPACE

          echo "Files:"
          find $GITHUB_WORKSPACE -type f

      - name: Check Artifacts Folder
        shell: bash
        run: |
          ls -R $GITHUB_WORKSPACE/artifacts || true
